### PR TITLE
New language: Italian

### PR DESCRIPTION
**Pull request by lukasitaly**
I have completed the translation of all strings into Italian.

### CODE REVIEW

**Comment by jovandeginste** [comment]
Thank you very much for your contribution! Would you mind running `prettier` or another linter on the json file, or manually fix the indentation? I can do this too, if you prefer.

**Comment by lukasitaly** [comment]
Don't worry about it, I will fix the indentation (you're doing enough for the community already) and translate the new strings. Did you add the new strings in the [messages.json](https://github.com/jovandeginste/workout-tracker/blob/master/translations/messages.json) file right? 
I won't get to it today but tomorrow or on Friday for sure.

**Comment by lukasitaly** [comment]
Done! And since I am bilingual meaning I speak Italian and German I also added the newly added strings to the German translation file.

Let me know if the indentation isn't what you had in mind.

**Comment by jovandeginste** [comment]
Looking good now, thank you very much!

**Comment by lukasitaly** [comment]
You're welcome, thank you for all your work! :)

**Pull request merged**
